# Tema 1.5: Vectores y Matrices con NumPy

## 1. Introducción a NumPy

NumPy (Numerical Python) es la librería fundamental para computación científica en Python. 

Su objeto principal es el **ndarray** (n-dimensional array), que es mucho más eficiente y potente operativamente que las listas estándar de Python.

Numpy no pertenece a la librería estándar de Python, por lo que debemos instalarla mediante pip:

In [1]:
#!pip install numpy # esto solo es necesario ejecutarlo una vez, descomentar línea y ejecutar en caso necesario.

Para usar numpy, primero debemos importar la librería:

In [2]:
import numpy as np

## 2. Creación de Arrays

Podemos crear arrays desde listas o usar funciones generadoras de NumPy.

In [3]:
# Desde listas
vector = np.array([1, 2, 3])
print(f"Vector:\n{vector}")

matriz = np.array([[1, 2], [3, 4]])
print(f"\nMatriz:\n{matriz}")

# Funciones generadoras especiales
ceros = np.zeros((2, 3))       # Matriz 2x3 de ceros
print(f"\nnp.zeros((2, 3)):\n{ceros}")
unos = np.ones((3, 2))         # Matriz 3x1 de unos
print(f"\nnp.ones((3, 2)):\n{unos}")
identidad = np.eye(3)         # Matriz identidad de 3x3
print(f"\nnp.eye(3):\n{identidad}")
rango = np.arange(0, 10, 2)    # Similar a range(): [0, 2, 4, 6, 8]
print(f"\nnp.arange(0, 10, 2):\n{rango}")
lineal = np.linspace(0, 1, 6)  # 6 puntos equidistantes entre 0 y 1
print(f"\nnp.linspace(0, 1, 6):\n{lineal}")

Vector:
[1 2 3]

Matriz:
[[1 2]
 [3 4]]

np.zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]]

np.ones((3, 2)):
[[1. 1.]
 [1. 1.]
 [1. 1.]]

np.eye(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.arange(0, 10, 2):
[0 2 4 6 8]

np.linspace(0, 1, 6):
[0.  0.2 0.4 0.6 0.8 1. ]


## 3. Propiedades y Acceso

Los arrays tienen propiedades importantes como su forma (`shape`), número de dimensiones (`ndim`) y tipo de dato (`dtype`).

La indexación es similar a las listas, pero permite indexación multidimensional `[fila, columna]` y **slicing**.

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(f"Matriz:\n{arr}")
print(f"shape: {arr.shape}")
print(f"arr[1, 2]: {arr[1, 2]}")  # Fila 1 (segunda), Columna 2 (tercera) -> 60
print(f"arr[0,:]: {arr[0, :]}")   # Todas las columnas de la fila 0
print(f"arr[:,2]: {arr[:,2]}")   # Todas las filas de la columna 2

print(f"\narr[:,2].reshape(-1,1):\n{arr[:,2].reshape(-1,1)}")   # reconfigurar datos a las filas que sean necesarias (-1) y 1 columna --> convertir a vector columna

Matriz:
[[10 20 30]
 [40 50 60]]
shape: (2, 3)
arr[1, 2]: 60
arr[0,:]: [10 20 30]
arr[:,2]: [30 60]

arr[:,2].reshape(-1,1):
[[30]
 [60]]


## 4. Operaciones vectorizadas

NumPy permite operar con arrays completos sin bucles `for` explícitos. Las operaciones se aplican elemento a elemento.

In [5]:
a = np.array([1, 2, 3])
print(f"a:\n{a}")

print(f"\nSuma con escalar (+): {a + 2}")
print(f"Multiplicación por escalar (*): {a * 2}")
print(f"Exponente escalar (**): {a ** 2}")

b = np.array([10, 10, 10])
print(f"\nb:\n{b}")

print(f"\nSuma a + b (+): {a + b}")
print(f"Producto escalar a * b (@): {a @ b}")

c = np.array([[10, 10, 10],[100, 100, 100]])
print(f"\nc:\n{c}")
print(f"\nProducto c * a (@):\n{(c @ a).reshape(-1,1)}")

a:
[1 2 3]

Suma con escalar (+): [3 4 5]
Multiplicación por escalar (*): [2 4 6]
Exponente escalar (**): [1 4 9]

b:
[10 10 10]

Suma a + b (+): [11 12 13]
Producto escalar a * b (@): 60

c:
[[ 10  10  10]
 [100 100 100]]

Producto c * a (@):
[[ 60]
 [600]]


También existen métodos de agregación muy eficientes:

In [6]:
datos = np.array([1, 5, 2, 8, 3])

print(f"Suma: {datos.sum()}")
print(f"Media: {datos.mean()}")
print(f"Máximo: {datos.max()}")

Suma: 19
Media: 3.8
Máximo: 8
