# T4.2c Ejercicios resueltos: Análisis de algoritmos iterativos

En este cuaderno encontrarás ejercicios de análisis de complejidad temporal de algoritmos iterativos.

**Recuerda** seguir los 5 pasos del procedimiento de análisis vistos en el cuaderno [T4.2a](./T4.2a%20Análisis%20de%20algoritmos%20iterativos.ipynb):
1. Identificar la talla $n$ del problema.
2. Determinar la unidad de medida de coste temporal (instrucción crítica).
3. Identificar si existen instancias diferentes (caso mejor y peor).
4. Caracterizar la función $T(n)$.
5. Proporcionar cotas de coste temporal en notación asintótica.

Nota: Revisa el [Anexo I](T4.5%20Anexo%20I%20-%20Escribiendo%20expresiones%20matemáticas%20en%20markdown.ipynb) de este tema para aprender a escribir ecuaciones matemáticas con LaTeX. 

---

## Ejercicio 1: Detección de repetidos

Dada una lista de objetos `a`, la siguiente función devuelve `True` si tiene elementos
repetidos. En caso contrario, si no hay ningún elemento repetido, la función devuelve
`False`.

Analiza de forma teórica el coste temporal de este algoritmo. 

In [ ]:
def hay_repetidos(a):
    res = False
    i = 0
    while i < len(a) and not res:
        j = 0
        while j < len(a) and not (j != i and a[j] == a[i]):
            j += 1
        if j < len(a):
            res = True
        i += 1
    return res

print(hay_repetidos([1, 2, 3, 4]))     
print(hay_repetidos([1, 2, 3, 1]))     
print(hay_repetidos([1, 1, 3, 4]))     

False
True
True


### Análisis de complejidad temporal

#### Paso 1: Talla

$n$, el número de elementos de la lista `a`.

#### Paso 2: Instrucción crítica

`j += 1` (alternativamente, podría ser `j < n`).

#### Paso 3: Instancias significativas

Sí hay:
- **Caso mejor**: Los dos primeros elementos son iguales: `a[0] == a[1]`.
- **Caso peor**: No hay ningún elemento repetido en la lista.

#### Paso 4: Función de coste temporal

- **Caso mejor**: El bucle interno encuentra `a[1] == a[0]` cuando `j=1`, ejecutando `j += 1` una sola vez. El bucle externo no continúa.
$$T^m(n) = 1 \; \text{i.c.}$$
- **Caso peor**: El bucle externo recorre todas las posiciones ($i=0, \dots, n-1$). Para cada $i$, el bucle interno recorre todo el array ($j=0, \dots, n-1$) sin encontrar repetidos.

$$T^p(n) = \sum_{i=0}^{n-1} \sum_{j=0}^{n-1} 1 = \sum_{i=0}^{n-1} n = n^2 \; \text{i.c.}$$

#### Paso 5: Cotas de complejidad

- $T^m(n) \in \Theta(1)$
- $T^p(n) \in \Theta(n^2)$
- $T(n) \in \Omega(1) \cap O(n^2)$

---

## Ejercicio 2: Contar primer repetido

Dada una lista de objetos `a` **ordenados ascendentemente**, la siguiente función cuenta cuántas veces aparece consecutivamente el primer elemento repetido que encuentre.
Si no hay repetidos, devuelve 0.

Analiza de forma teórica el coste temporal de este algoritmo. 

In [4]:
def contar_primer_repetido(a):
    """Precondición: a está ordenado ascendentemente."""
    cont = 0
    i = 0
    repe = False
    while i < len(a) - 1 and not repe:
        j = i + 1
        repe = (a[j] == a[i])
        while j < len(a) and a[j] == a[i]:
            j += 1
        if repe:
            cont = j - i
        i += 1
    return cont

print(contar_primer_repetido([1, 2, 3, 4, 5]))     
print(contar_primer_repetido([1, 1, 3, 4, 5]))     
print(contar_primer_repetido([1, 3, 3, 3, 3]))     

0
2
4


### Análisis de complejidad temporal

#### Paso 1: Talla

$n$, el número de elementos del array `a`.

#### Paso 2: Instrucción crítica

La guarda del bucle interno `j < n and a[j] == a[i]`.

#### Paso 3: Instancias significativas

Sí hay.
- **Caso mejor**: `a[0]` está repetido una sola vez consecutiva, es decir, `a[0] == a[1]` y `a[0] != a[2]`.
- **Caso peor**: No hay repetidos en el array, o bien `a[0]` está repetido en todo el array.

#### Paso 4: Función de coste temporal

- **Caso mejor**: El bucle externo ejecuta una sola iteración ($i=0$). La guarda del bucle interno se evalúa 2 veces.
$$T^m(n) = 2 \; \text{i.c.}$$
- **Caso peor** (sin repetidos): El bucle externo recorre $i=0, \dots, n-2$. Para cada $i$, el bucle interno evalúa la guarda una sola vez (ya que `a[i+1] != a[i]`).

$$T^p(n) = \sum_{i=0}^{n-2} 1 = n - 1 \; \text{i.c.}$$

#### Paso 5: Cotas de complejidad

- $T^m(n) \in \Theta(1)$
- $T^p(n) \in \Theta(n)$
- $T(n) \in \Omega(1) \cap O(n)$

---

## Ejercicio 3: Comparación de sumas en una matriz

Dada una matriz cuadrada `a` de valores numéricos, la siguiente función comprueba si la suma de los elementos que están por debajo de la diagonal principal, menos la de los que están por encima, coincide con la suma de los elementos de la diagonal principal.

In [8]:
def sum_below_above(a):
    """Precondición: a es una matriz cuadrada."""
    sum_below = sum_diag = sum_above = 0
    for i in range(len(a)):
        for j in range(len(a)):
            if j < i:
                sum_below += a[i][j]
            elif j == i:
                sum_diag += a[i][i]
            else:
                sum_above += a[i][j]
    return sum_below - sum_above == sum_diag

import numpy as np
m = np.arange(16).reshape(4,4)
print(m)
print(f"¿Coincide? {sum_below_above(m)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
¿Coincide? True


### Análisis de complejidad temporal

#### Paso 1: Talla

$n$, el orden de la matriz cuadrada `a`.

#### Paso 2: Instrucción crítica

El cuerpo del bucle interno (la evaluación `j < i`), de coste unitario.

#### Paso 3: Instancias significativas

No. Los dos bucles son recorridos cuyo coste depende únicamente de la talla del problema.

#### Paso 4: Función de coste temporal

$$T(n) = \sum_{i=0}^{n-1} \sum_{j=0}^{n-1} 1 = \sum_{i=0}^{n-1} n = n^2 \; \text{i.c.}$$

#### Paso 5: Cotas de complejidad

- $T(n) \in \Theta(n^2)$ (coste cuadrático)

---

## Ejercicio 4: Codificación de una matriz (completa)

La siguiente función codifica una matriz cuadrada de caracteres cambiando determinados caracteres (aquellos que son letras) por otros codificados sumando un valor `v` a su código numérico (código ASCII).

In [ ]:
def codify_matrix(a, v):
    """Precondición: a es una matriz cuadrada de caracteres."""
    for i in range(len(a)):
        for j in range(len(a)):
            aux = a[i][j]
            if aux.isalpha():
                a[i][j] = chr(ord(aux) + v)

m = [['a', 'b', '1'], ['c', '2', 'd'], ['3', 'e', 'f']]
print("Antes:", m)
codify_matrix(m, 1)
print("Después:", m)

Antes: [['a', 'b', '1'], ['c', '2', 'd'], ['3', 'e', 'f']]
Después: [['b', 'c', '1'], ['d', '2', 'e'], ['3', 'f', 'g']]


### Análisis de complejidad temporal

#### Paso 1: Talla

$n$, el orden de la matriz cuadrada `a`.

#### Paso 2: Instrucción crítica

`aux = a[i][j]`.

#### Paso 3: Instancias significativas

No. Los dos bucles son recorridos cuyo coste depende únicamente de la talla del problema.

#### Paso 4: Función de coste temporal

$$T(n) = \sum_{i=0}^{n-1} \sum_{j=0}^{n-1} 1 = \sum_{i=0}^{n-1} n = n^2 \; \text{i.c.}$$

#### Paso 5: Cotas de complejidad

- $T(n) \in \Theta(n^2)$ (coste cuadrático)

---

## Ejercicio 5: Codificación de una matriz (triángulo superior)

La siguiente función codifica una matriz cuadrada de caracteres cambiando determinados caracteres (aquellos situados **por encima de la diagonal principal** que son letras)
por otros codificados sumando un valor `v` a su código numérico (código ASCII).

In [11]:
def codify_matrix_upper(a, v):
    """Precondición: a es una matriz cuadrada de caracteres."""
    for i in range(len(a)):
        for j in range(i + 1, len(a)):
            aux = a[i][j]
            if aux.isalpha():
                a[i][j] = chr(ord(aux) + v)

m = [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
print("Antes:", m)
codify_matrix_upper(m, 10)
print("Después:", m)

Antes: [['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']]
Después: [['a', 'l', 'm'], ['d', 'e', 'p'], ['g', 'h', 'i']]


### Análisis de complejidad temporal

#### Paso 1: Talla

$n$, el orden de la matriz cuadrada `a`.

#### Paso 2: Instrucción crítica

`aux = a[i][j]`.

#### Paso 3: Instancias significativas

No. Los dos bucles son recorridos cuyo coste depende únicamente de la talla del problema.

#### Paso 4: Función de coste temporal

$$T(n) = \sum_{i=0}^{n-1} \sum_{j=i+1}^{n-1} 1 = \sum_{i=0}^{n-1} (n - 1 - i) = \frac{((n-1) + 0)\cdot n}{2} = \frac{n^2 - n}{2}\; \text{i.c.}$$

#### Paso 5: Cotas de complejidad

- $T(n) \in \Theta(n^2)$ (coste cuadrático)