# T4.2a Análisis de algoritmos iterativos

## 1. Procedimiento de análisis

Para analizar el coste temporal de un algoritmo iterativo, seguimos estos pasos:
1. Identificar la **talla** $n$ del problema.
2. Determinar la **unidad de medida de coste temporal**.
    * Si se usa el método de la instrucción crítica (i.c.), debemos identificar dicha instrucción.
3. Identificar si existen **instancias** diferentes o no, y en tal caso, describir los dos más significativas (caso mejor y peor).
4. **Caracterizar la función $T(n)$** para el caso único, o para el mejor y para el peor caso.
    * Expresión matemática que permite contar el número de veces que se ejecuta la i.c. en función de $n$.
    * Generalmente suele consistir en contar el número de iteraciones.
        * Esto depende de cómo se reduzca la talla tras cada iteración.
5. Proporcionar **cotas de coste temporal en notación asintótica**.

## 2. El efecto de la reducción de la talla en el coste temporal

Consideremos el **problema del cálculo de potencias**: dada una base $a$ y un exponente $n$, calcula la potencia $a^n$.


### 2.1 Primera aproximación

Consideramos una estrategia sencilla y popular para resolver el cálculo de la potencia:

$$a^n = \left\{
\begin{array}{cl}
a \cdot a^{n-1} &  \text{si} & n>0 \\
1 &  \text{si}  & n = 0
\end{array} \right. $$





In [35]:
def potencia(a, n):
    pot = 1
    while n > 0:
        pot = pot * a
        n -= 1
    return pot

print(f"2^10: {potencia(2,10)}")
print(f"2^19: {potencia(2,19)}")

2^10: 1024
2^19: 524288


**Análisis de complejidad temporal:**

1. **Talla**: es el exponente $n$. 
    * El exponente condiciona el número de pasos que debe realizar el algoritmo para finalizar. 
    * Es por tanto es el indicador del volumen de operaciones a realizar.
2. **Instrucción crítica**: `n > 0`.
3. **Instancias diferentes**: no.
    * El algoritmo siempre se comporta igual con independencia del valor de los datos (excepto $n$, que representa la talla).
        * Para este algoritmo en concreto, da igual el valor de $a$: el algoritmo siempre se comporta igual para una talla (exponente) $n$ dada.
4. **Función de coste temporal**: 
    * La guarda del bucle se ejecuta $n+1$ veces.
    * $T(n) = n + 1 \;$ i.c.
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n)$ (coste lineal)

Notar que en cada paso se resuelve un sub-problema de talla reducida.

En cada paso del algoritmo se decrementa la talla en una unidad: **reducción aritmética de la talla**.

Las estructuras de control de repetición que aplican reducciones aritméticas de talla conllevan **costes lineales**.

¿Podemos adoptar un enfoque más agresivo, con una reducción de la talla de mayor magnitud paso a paso?

### 2.2 Segunda aproximación

Consideramos una aproximación alternativa al cálculo de la potencia:

$$a^n = \left\{
\begin{array}{cl}
(a \cdot a)^{\frac{n}{2}} &  \text{si} & n>1 \text{ y } n \text{ es par} \\
a \cdot (a \cdot a)^{\frac{n}{2}} &  \text{si} & n>1 \text{ y } n \text{ es impar} \\
a & \text{si} & n=1 \\
1 &  \text{si}  & n = 0
\end{array} \right.$$

In [13]:
def potencia_v2(a, n, verbose=False):
    if n == 0: 
        return 1
    pot = 1
    i = 0
    while n > 1:
        i += 1
        if verbose: print(f"- Iter. {i} ")
        if n % 2 == 1:
            if verbose: print(f"  - pot = {pot} * {a} = {pot*a}")
            pot = pot * a
        if verbose: print(f"  - a = {a} * {a} = {a*a}")
        a = a * a
        if verbose: print(f"  - n = {n} / 2 = {n//2}")
        n = n // 2
    pot = pot * a
    if verbose: print(f"- pot = {pot} * {a} = {pot * a}")
    return pot

print(f"2^10: {potencia_v2(2,10, verbose=False)}")
print(f"2^19: {potencia_v2(2,19, verbose=False)}")

2^10: 1024
2^19: 524288


**Análisis de complejidad temporal:**

1. **Talla**: es el exponente $n$. 
    * Mismo razonamiento que en la primera aproximación.
2. **Instrucción crítica**: `n > 1`.
3. **Instancias diferentes**: no.
    * Mismo razonamiento que en la primera aproximación.
4. **Función de coste temporal**: 
    * La talla se divide por 2 en cada paso.
    * Analizamos como se reduce la talla en cada paso para determinar el número de iteraciones.
        * Inicialmente: talla $n$
        * Tras la 1a iteración: talla $n/2$
        * Tras la 2a iteración: talla $n/2^2$
        * Tras la 3a iteración: talla $n/2^3$
        * ...
        * Tras la última iteración: talla $n/2^{\lfloor \log_2n \rfloor} \; = n/n = 1$
    * El número de iteraciones es $\lfloor \log_2n \rfloor$.
    * Notar que la instrucción de guarda del bucle siempre se ejecuta 1 vez más.
    * $T(n) = \lfloor \log_2 n \rfloor + 1 \;$ i.c.

5. **Cotas de complejidad**:
    * $T(n) \in \Theta(\log n)$ (coste logarítmico)

En cada paso del algoritmo divide la talla por la mitad: **reducción geométrica de la talla**.

Las estructuras de control de repetición que aplican reducciones geométricas de talla conllevan **costes logarítmicos**.

## 3. Uso de sumatorios para el análisis de algoritmos iterativos


### 3.1 Aspectos generales

En general, usaremos sumatorios ($\sum$) con variables índice definidos para ayudarnos con el conteo de las instrucciones críticas ejecutadas. 

La expresión

$$\sum_{i=1}^{n} 1$$

nos indica que queremos sumar 1 tantas veces como iteraciones se realizan desde que $i=1$ hasta que $i=n$, con incrementos unitarios de $i$. 

Dicha expresión nos permitiría contar el número de iteraciones que realiza este bucle `while`: 

```python
def f1(n):
    i = 1
    while (i <= n):
        i += 1
```

o equivalentemente, este bucle `for` con un `range`:

```python
def f2(n):
    for i in range(1, n+1):
        pass
```

En total se realizarán $(n - 1 + 1)$ iteraciones (`valor_i_final - valor_i_inicial + 1`). Por tanto:

$$\sum_{i=1}^{n} 1 = n$$

ya que sumamos $(n - 1 + 1)$ veces el valor $1$.

Notar que, cuando el valor del cuerpo del sumatorio no depende del índice ($i$), podemos ajustar la inicialización y el límite superior de dicho índice a conveniencia:

$$\sum_{i=1}^{n} 1 = \sum_{i=0}^{n-1} 1 = n$$



### 3.2 Suma de progresiones

El cálculo de la complejidad suele requerir realizar la suma de una secuencia de términos que forman progresiones aritméticas o geométricas.


#### 3.2.1 Suma de progresión aritmética

Una progresión aritmética $a$ es una sucesión de números tales que la diferencia de dos términos sucesivos cualesquiera de la secuencia es una constante $d$.

Ejemplos: 
- $a = 1,1,1,1\;$ ($d=0$)
- $a = 1,2,3,4,5\;$ ($d=1$)
- $a = 4,7,10\;$ ($d=3$)

Formalmente: $a = a_0, a_1, \dots,  a_i, \dots, a_{n-1}$, donde:

$$a_i = a_0 + i \cdot d $$

La suma de los $n$ primeros términos de una progresión aritmética es:

$$S_n = \sum_{i=0}^{n-1} (a_0 + i \cdot d) = \frac{(a_0 + a_{n-1}) \cdot n}{2}$$

Ejemplos con progresiones concretas: 
- $a = 1,1,1,1$
   + $S_n = \sum_{i=0}^{3} (1 + i \cdot 0) = 1 + 1 + 1 + 1 = \frac{(1+1) \cdot 4}{2} = 4$
- $a = 1,2,3,4,5$
   + $S_n = \sum_{i=0}^{4} (1 + i \cdot 1) = 1 + 2 + 3 + 4 + 5 = \frac{(1+5) \cdot 5}{2} = 15$
- $a = 4,7,10$
   + $S_n = \sum_{i=0}^{2} (4 + i \cdot 3) = 4 + 7 + 10 = \frac{(4+10) \cdot 3}{2} = 21$


Ejemplos paramétricos para progresiones de longitud dependiente de $n$ (la talla):

$$ \sum_{i=1}^{n} i = 1 + 2 + 3 + \dots  + n = \frac{(1+n)\cdot n}{2} $$

$$ \sum_{i=1}^{n-1} (n - i + 1) = n + (n-1) + ... + 2 = \frac{(n + 2) \cdot (n-1)}{2} $$

#### 3.2.2 Suma de progresión geométrica

Una progresión geométrica $a$ es una sucesión de números tales que cada término se obtiene multiplicando el anterior por una constante $r$ llamada razón.

Ejemplos: 
- $a = 1, 2, 4, 8\;$ ($r=2$)
- $a = 3, 6, 12, 24\;$ ($r=2$)
- $a = 1, 1/2, 1/4, 1/8\;$ ($r=1/2$)

Formalmente: $a = a_0, a_1, \dots,  a_i, \dots, a_{n-1}$, donde:

$$a_i = a_0 \cdot r^i $$

La suma de los $n$ primeros términos de una progresión geométrica ($r \neq 1$) es:

$$S_n = \sum_{i=0}^{n-1} (a_0 \cdot r^i) = \frac{a_{n-1} \cdot r - a_0}{r - 1}$$

Ejemplos con progresiones concretas: 
- $a = 1, 2, 4, 8$
   + $S_n = \frac{8*2 - 1}{2 - 1} = 15$
- $a = 3, 6, 12, 24$
   + $S_n = \frac{24*2 - 3}{2 - 1} = 45$
- $a = 1, 1/2, 1/4, 1/8$
   + $S_n = \frac{(1/8)*(1/2) - 1}{1/2 - 1} = \frac{1/16 - 1}{-1/2} = \frac{-15/16}{-1/2} = \frac{15}{8} = 1.875$

Ejemplos paramétricos para progresiones de longitud dependiente de $n$ (la talla):

$$ \sum_{i=0}^{n} 2^i = 1 + 2 + 4 + \dots + 2^{n-1} + 2^n = \frac{2^n\cdot 2 - 1}{2-1} = 2^{n+1} -1$$



### 3.3 Bucles anidados

Si tenemos bucles anidados, entonces anidamos también los sumatorios, resolviéndolos desde dentro hacia afuera. Por ejemplo:

```python
def f3(n):
    for i in range(1, n+1):
        for j in range(n+1):
            pass
```

El número de iteraciones que realiza este algoritmo es:

$$ \sum_{i=1}^{n} \sum_{j=0}^{n} 1 = \sum_{i=1}^{n} (n + 1) = n \cdot (n+1) = n^2 + n$$


## 4. Análisis de algoritmos iterativos

### 4.1 Impresión de bloques de asteriscos

Vamos a analizar el coste de imprimir $n$ líneas con $n$ asteriscos cada una.

In [ ]:
def print_bloque_asteriscos(n):
    for i in range(n):
        for j in range(n):
            print('*', end='')
        print()

print_bloque_asteriscos(3)

***
***
***


**Análisis de complejidad temporal:**

1. **Talla**: $n$ (número de líneas y asteriscos por línea). 
2. **Instrucción crítica**: `print('*', end='')`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * El bucle externo se ejecuta $n$ veces ($i=0, \dots, n-1$).
    * El bucle interno se ejecuta $n$ veces para cada iteración de $i$ ($j=0, \dots, n-1$).
    $$ T(n) = \sum_{i=0}^{n-1} \sum_{j=0}^{n-1} 1 = \sum_{i=0}^{n-1} n = n^2 \; \text{i.c.}$$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n^2)$ (coste cuadrático)

### 4.2 Impresión de triángulos de asteriscos 

Vamos a analizar el coste de imprimir $n$ líneas de longitud creciente $1, 2, \dots n$.

In [17]:
def print_triangulo_asteriscos(n):
    for i in range(1, n+1):
        for j in range(i):
            print('*', end='')
        print()

print_triangulo_asteriscos(4)

*
**
***
****


**Análisis de complejidad temporal:**

1. **Talla**: $n$ (número de líneas).
2. **Instrucción crítica**: `print('*', end='')`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * El bucle externo se ejecuta $n$ veces ($i=1, \dots, n$).
    * El bucle interno se ejecuta $i$ veces para cada valor de $i$.


    $$ T(n) = \sum_{i=1}^{n} \sum_{j=0}^{i-1} 1 = \sum_{i=1}^{n} i = \frac{(1+n)n}{2} = \frac{n^2 + n}{2} \; \text{i.c.} $$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n^2)$ (coste cuadrático)

### 4.3 Suma de factoriales

Supongamos que queremos calcular la suma de los primeros $n$ factoriales naturales:

$$\sum_{i=0}^{n} i!$$


#### 4.3.1 Primera aproximación

Esta es nuestra primera aproximación: 

In [21]:
def factorial(i):
    f = 1
    for k in range(1, i + 1):
        f *= k
    return f

def suma_fact_v1(n):
    resultado = 0
    for i in range(n + 1):
        resultado += factorial(i)
    return resultado

print(suma_fact_v1(3))

10


**Análisis de complejidad temporal:**

1. **Talla**: $n$.
2. **Instrucción crítica**: `f *= k`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * El bucle de `suma_fact_v1` se ejecuta $n+1$ veces ($i=0, \dots, n$).
    * Para cada $i$, se llama a `factorial(i)`, cuyo bucle interno se ejecuta $i$ veces.

      $$T(n) = \sum_{i=0}^{n} \sum_{k=1}^{i} 1 = \sum_{i=0}^{n} i = \frac{n(n+1)}{2} \; \text{i.c.}$$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n^2)$ (coste cuadrático)

#### 4.3.2 Segunda aproximación

En nuestra segunda aproximación reaprovechamos el cálculo del factorial anterior para evitar repetir cálculos:

In [20]:
def suma_fact_v2(n):
    fact = 1
    resultado = fact
    for i in range(1, n + 1):
        fact *= i
        resultado += fact
    return resultado

print(suma_fact_v2(3))

10


**Análisis de complejidad temporal:**

1. **Talla**: $n$.
2. **Instrucción crítica**: `f *= i`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * El bucle se ejecuta $n$ veces ($i=1, \dots, n$).

    $$T(n) = \sum_{i=1}^{n} 1 = n \; \text{i.c.}$$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n)$ (coste lineal)

> Notar que hemos pasado de un coste cuadrático $\Theta(n^2)$ de la primera aproximación a un coste lineal $\Theta(n)$ en la segunda. Ambos algoritmos resuelven el mismo problema. ¡Eso es una gran ganancia en eficiencia computacional!

### 4.4 Suma de elementos por debajo de la diagonal de una matriz

#### 4.4.1 Primera aproximación

In [27]:
def suma_diagonal_v1(m):
    n = len(m)
    suma = 0
    for i in range(n):
        for j in range(n):
            if i > j:
                suma += m[i][j]
    return suma

import numpy as np
m = np.arange(16).reshape(4,4)
print(m)
print(f"Suma elementos inferiores a la diagonal: {suma_diagonal_v1(m)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Suma elementos inferiores a la diagonal: 60


**Análisis de complejidad temporal:**

1. **Talla**: $n$ (dimensión de la matriz cuadrada $n \times n$).
2. **Instrucción crítica**: `if i > j`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * Los dos bucles anidados recorren todas las posiciones de la matriz.

    $$T(n) = \sum_{i=0}^{n-1} \sum_{j=0}^{n-1} 1 = n^2 \; \text{i.c.}$$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n^2)$ (coste cuadrático)

#### 4.4.2 Segunda aproximación

In [30]:
def suma_diagonal_v2(m):
    n = len(m)
    suma = 0
    for i in range(1, n):
        for j in range(i):
            suma += m[i][j]
    return suma

import numpy as np
m = np.arange(16).reshape(4,4)
print(m)
print(f"Suma elementos inferiores a la diagonal (v2): {suma_diagonal_v2(m)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Suma elementos inferiores a la diagonal (v2): 60


**Análisis de complejidad temporal:**

1. **Talla**: $n$ (dimensión de la matriz cuadrada $n \times n$).
2. **Instrucción crítica**: `suma += m[i][j]`.
3. **Instancias diferentes**: no.
4. **Función de coste temporal**: 
    * El bucle externo va de 1 a $n-1$. El interno va de 0 a $i-1$.

    $$T(n) = \sum_{i=1}^{n-1} \sum_{j=0}^{i-1} 1 = \sum_{i=1}^{n-1} i = \frac{(1 + n-1)(n-1)}{2} = \frac{n^2 - n}{2} \; \textit{i.c.} $$
    
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n^2)$ (coste cuadrático)

### 4.5. Búsqueda binaria (iterativa)

En el tema anterior vimos la búsqueda binaria, en su versión recursiva. Aquí presentamos y analizamos la versión iterativa equivalente. 

Notar que la zona de búsqueda se reduce a la mitad tras cada iteración.

In [ ]:
def busqueda_binaria(a, x):
    ini = 0
    fin = len(a) - 1
    encontrado = False
    while ini <= fin and not encontrado:
        medio = (ini + fin) // 2
        if a[medio] == x:
            encontrado = True
        elif a[medio] < x:
            ini = medio + 1
        else:
            fin = medio - 1
    return medio if encontrado else -1

**Análisis de complejidad temporal:**

1. **Talla**: $n$ (número de elementos en la lista).
2. **Instrucción crítica**: `ini <= fin`.
3. **Instancias diferentes**: sí.
    * **Caso mejor**: El elemento buscado está en la posición central. 
    * **Caso peor**: El elemento no está en la lista. 
4. **Función de coste temporal**:
    * En cada iteración la zona de búsqueda se reduce a la mitad: **reducción geométrica**.
    * El algoritmo se detiene cuando la zona de búsqueda tiene cero elementos, tras $\log_2 n + 1$ iteraciones.
    * $T^m(n) = 2 \;$ i.c.
    * $T^p(n) = \lfloor \log_2 n \rfloor + 1 \;$ i.c.
5. **Cotas de complejidad**:
    * $T^m(n) \in  \Theta(1)$
    * $T^p(n) \in  \Theta(\log n)$
    * $T(n) \in \Omega(1) \cap O(\log n)$

### 4.6 Mezcla natural de listas ordenadas

Dadas dos listas ordenadas $A$ y $B$, obtener una lista $C$ ordenada con los elementos de ambas.

In [ ]:
def mezcla(a, b):
    i = j = k = 0
    c = [0] * (len(a)+len(b)) # inicializamos C como len(A) + len(B), con todo ceros
    
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            c[k] = a[i]
            i += 1
        else:
            c[k] = b[j]
            j += 1
        k += 1
        
    # Añadir elementos restantes manualmente
    while i < len(a):
        c[k] = a[i]
        i += 1
        k += 1

    while j < len(b):
        c[k] = b[j]
        j += 1
        k += 1
    return c

print(f"Mezcla [1, 3, 5] y [2, 4, 6]: {mezcla([1, 3, 5], [2, 4, 6])}")

Mezcla [1, 3, 5] y [2, 4, 6]: [1, 2, 3, 4, 5, 6]


**Análisis de complejidad temporal:**

1. **Talla**: $n = len(a) + len(b)$.
2. **Instrucción crítica**: `k += 1`.
    * Notar que esta instrucción aparece en dos bucles diferentes y en tres ocasiones.
    * Podríamos pensar que son instrucciones diferentes e independientes, pero no. La ejecución de cualquiera de las tres conlleva el mismo efecto: incrementar la variable de recorrido de la secuencia C. Por tanto, conceptualmente hablando, representan una sola instrucción. 
3. **Instancias diferentes**: no.
    * Con independencia de los valores de las listas, todos los elementos de $a$ y $b$ deben acabar en $c$.
    * Por tanto, la instrucción `k += 1` se ejecutará siempre el mismo número de veces.
4. **Función de coste temporal**: 
    * Cada elemento de las listas originales se añade a la lista resultante exactamente una vez.
    * $T(n) = len(a) + len(b) = n \;$ i.c.
5. **Cotas de complejidad**:
    * $T(n) \in \Theta(n)$ (coste lineal)